# file: .github/workflows/wandb-check.yml
name: Check W&B Model Artifacts

on:
  push:
    branches:
      - prod

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wandb dataiku-api-client pandas urllib3

      - name: Run W&B model check
        run: python scripts/check_wandb_models.py
       
     
